# NUMPY


In [48]:
import numpy as np

In [49]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [50]:
arr[0]

1

In [51]:
arr[1]

2

### numpy array vs normal array

In [52]:
import sys
from array import *
ar=array("i",[1,2,3,4])


In [53]:
#size comparision

In [54]:
sys.getsizeof(ar)

96

In [55]:
arr.nbytes

16

In [56]:
l=range(1000)
ll=np.arange(1000)
print(sys.getsizeof(1)*1000)
print(ll.size*ll.itemsize)


28000
4000


In [78]:
#speed  comparision

import time
l1=range(10000)
l2=range(10000)
a1=np.arange(10000)
a2=np.arange(10000)



In [87]:
start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print((time.time()-start)*1000)


4.045009613037109


In [88]:
start=time.time()
result=a1+a2

print((time.time()-start)*1000)


1.5187263488769531


In [90]:
a=np.array([[2,3],[4,5],[6,7]], dtype=np.float64)
a


array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [92]:
a=np.array([[2,3],[4,5],[6,7]], dtype=np.int64)
a

array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int64)

In [93]:
a.ndim

2

In [94]:
a.size  #no of elements

6

In [96]:
a.itemsize #size of one element

8

In [97]:
a.shape

(3, 2)

In [100]:
l=np.zeros((3,4))
l

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
l=np.ones((4,4))
l

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
range(10)


range(0, 10)

In [103]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])