# NUMPY

In [1]:
from array import *
ar=array('i',[1,2,3,4])


In [2]:
ar


array('i', [1, 2, 3, 4])

In [3]:
for i in ar:print(i)

1
2
3
4


In [4]:
import sys
sys.getsizeof(ar)

96

In [5]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4],dtype=int)

In [7]:
arr

array([1, 2, 3, 4])

In [8]:
arr.size


4

In [9]:
arr.nbytes


16

In [10]:
type(arr)

numpy.ndarray

In [11]:
len(arr)

4

In [12]:
arr.ndim

1

In [13]:
arr.shape

(4,)

In [14]:
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [15]:
arr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [16]:
arr.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [17]:
arr.shape=(2,2)

In [18]:
arr

array([[1, 2],
       [3, 4]])

In [19]:
x=[1,2,3]
y=[3,4,5]
z=[5,6,7]
ashaya=np.array([x,y,z])

In [20]:
ashaya


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [21]:
r=range(1,10,2)

In [22]:
r

range(1, 10, 2)

In [23]:
for i in r:print(i)

1
3
5
7
9


In [24]:
r[4]

9

In [25]:
r[3]*2


14

In [26]:
for i in r:print(i)

1
3
5
7
9


In [27]:
sys.getsizeof(r)

48

In [28]:
rr=np.arange(1,10,2)

In [29]:
rr.nbytes

20

In [30]:
rrr=np.arange(24)

In [31]:
rrr.reshape(6,4,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [32]:
a=np.array([1,4,3])
b=np.array([2,5,6])
np.add(a,b)

array([3, 9, 9])

In [33]:
np.multiply(a,b)

array([ 2, 20, 18])

In [34]:
s=np.array([[1,2],[3,4]])

In [35]:
s

array([[1, 2],
       [3, 4]])

In [36]:
np.sum(s)

10

In [37]:
np.sum(s,axis=0)

array([4, 6])

# PANDAS

In [38]:
import pandas as pd

In [39]:
import os

In [41]:
data_csv=pd.read_csv("D:\Data Science\Toyota.csv",index_col=0,na_values=["??"])

In [42]:
data_csv

Price   Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  23.0  46986.0   Diesel   90       1.0          0  2000  three   
1     13750  23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950  24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950  26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750  30.0  38500.0   Diesel   90       0.0          0  2000      3   
...     ...   ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500   NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845  72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500   NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250  70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950  76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [43]:
data2=data_csv.copy(deep=False);

In [44]:
data2.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [45]:
data2.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [46]:
data2.size

14360

In [47]:
data2.shape

(1436, 10)

In [48]:
data2.memory_usage()

Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [49]:
data2.head(10)

Price   Age       KM FuelType    HP  MetColor  Automatic    CC  Doors  \
0  13500  23.0  46986.0   Diesel    90       1.0          0  2000  three   
1  13750  23.0  72937.0   Diesel    90       1.0          0  2000      3   
2  13950  24.0  41711.0   Diesel    90       NaN          0  2000      3   
3  14950  26.0  48000.0   Diesel    90       0.0          0  2000      3   
4  13750  30.0  38500.0   Diesel    90       0.0          0  2000      3   
5  12950  32.0  61000.0   Diesel    90       0.0          0  2000      3   
6  16900  27.0      NaN   Diesel  ????       NaN          0  2000      3   
7  18600  30.0  75889.0      NaN    90       1.0          0  2000      3   
8  21500  27.0  19700.0   Petrol   192       0.0          0  1800      3   
9  12950  23.0  71138.0   Diesel  ????       NaN          0  1900      3   

   Weight  
0    1165  
1    1165  
2    1165  
3    1165  
4    1170  
5    1170  
6    1245  
7    1245  
8    1185  
9    1105

In [50]:
data2.tail()

Price   Age       KM FuelType   HP  MetColor  Automatic    CC Doors  \
1431   7500   NaN  20544.0   Petrol   86       1.0          0  1300     3   
1432  10845  72.0      NaN   Petrol   86       0.0          0  1300     3   
1433   8500   NaN  17016.0   Petrol   86       0.0          0  1300     3   
1434   7250  70.0      NaN      NaN   86       1.0          0  1300     3   
1435   6950  76.0      1.0   Petrol  110       0.0          0  1600     5   

      Weight  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114

In [51]:
data2.at[4,"FuelType"]

'Diesel'

In [52]:
data2.iat[4,3]

'Diesel'

In [53]:
data2.head()


Price   Age       KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986.0   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937.0   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711.0   Diesel  90       NaN          0  2000      3    1165
3  14950  26.0  48000.0   Diesel  90       0.0          0  2000      3    1165
4  13750  30.0  38500.0   Diesel  90       0.0          0  2000      3    1170

In [54]:
data2.iat[0,1]=1340

In [55]:
data2.head()

Price     Age       KM FuelType  HP  MetColor  Automatic    CC  Doors  \
0  13500  1340.0  46986.0   Diesel  90       1.0          0  2000  three   
1  13750    23.0  72937.0   Diesel  90       1.0          0  2000      3   
2  13950    24.0  41711.0   Diesel  90       NaN          0  2000      3   
3  14950    26.0  48000.0   Diesel  90       0.0          0  2000      3   
4  13750    30.0  38500.0   Diesel  90       0.0          0  2000      3   

   Weight  
0    1165  
1    1165  
2    1165  
3    1165  
4    1170

In [56]:
data_csv

Price     Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  1340.0  46986.0   Diesel   90       1.0          0  2000  three   
1     13750    23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950    24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950    26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750    30.0  38500.0   Diesel   90       0.0          0  2000      3   
...     ...     ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500     NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845    72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500     NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250    70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950    76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [57]:
data3=data_csv.copy(deep=True)

In [58]:
data3.iat[0,1]=450

In [59]:
data3

Price    Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  450.0  46986.0   Diesel   90       1.0          0  2000  three   
1     13750   23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950   24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950   26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750   30.0  38500.0   Diesel   90       0.0          0  2000      3   
...     ...    ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500    NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845   72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500    NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250   70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950   76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [60]:
data_csv

Price     Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  1340.0  46986.0   Diesel   90       1.0          0  2000  three   
1     13750    23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950    24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950    26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750    30.0  38500.0   Diesel   90       0.0          0  2000      3   
...     ...     ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500     NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845    72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500     NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250    70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950    76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [61]:
import pandas as pd
import os

In [62]:
data_csv=pd.read_csv("Toyota.csv",index_col=0,na_values=['??'])

In [63]:
data_csv

Price   Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500  23.0  46986.0   Diesel   90       1.0          0  2000  three   
1     13750  23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950  24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950  26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750  30.0  38500.0   Diesel   90       0.0          0  2000      3   
...     ...   ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500   NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845  72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500   NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250  70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950  76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [64]:
data_csv.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [65]:
data_csv.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [68]:
data_csv.size

14360

In [69]:
data_csv.shape

(1436, 10)

In [70]:
data_csv.memory_usage()

Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [71]:
data_csv.ndim

2

In [72]:
data_csv['Doors']

0       three
1           3
2           3
3           3
4           3
        ...  
1431        3
1432        3
1433        3
1434        3
1435        5
Name: Doors, Length: 1436, dtype: object

In [73]:
data_csv.head(10)

Price   Age       KM FuelType    HP  MetColor  Automatic    CC  Doors  \
0  13500  23.0  46986.0   Diesel    90       1.0          0  2000  three   
1  13750  23.0  72937.0   Diesel    90       1.0          0  2000      3   
2  13950  24.0  41711.0   Diesel    90       NaN          0  2000      3   
3  14950  26.0  48000.0   Diesel    90       0.0          0  2000      3   
4  13750  30.0  38500.0   Diesel    90       0.0          0  2000      3   
5  12950  32.0  61000.0   Diesel    90       0.0          0  2000      3   
6  16900  27.0      NaN   Diesel  ????       NaN          0  2000      3   
7  18600  30.0  75889.0      NaN    90       1.0          0  2000      3   
8  21500  27.0  19700.0   Petrol   192       0.0          0  1800      3   
9  12950  23.0  71138.0   Diesel  ????       NaN          0  1900      3   

   Weight  
0    1165  
1    1165  
2    1165  
3    1165  
4    1170  
5    1170  
6    1245  
7    1245  
8    1185  
9    1105

In [74]:
data_csv.tail()

Price   Age       KM FuelType   HP  MetColor  Automatic    CC Doors  \
1431   7500   NaN  20544.0   Petrol   86       1.0          0  1300     3   
1432  10845  72.0      NaN   Petrol   86       0.0          0  1300     3   
1433   8500   NaN  17016.0   Petrol   86       0.0          0  1300     3   
1434   7250  70.0      NaN      NaN   86       1.0          0  1300     3   
1435   6950  76.0      1.0   Petrol  110       0.0          0  1600     5   

      Weight  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114

In [75]:
data_csv.at[4,'FuelType']

'Diesel'

In [76]:
data_csv.iat[4,3]

'Diesel'

In [77]:
data_csv.loc[1:4,'KM':'MetColor']

KM FuelType  HP  MetColor
1  72937.0   Diesel  90       1.0
2  41711.0   Diesel  90       NaN
3  48000.0   Diesel  90       0.0
4  38500.0   Diesel  90       0.0

In [78]:
data_csv.dtypes

Price          int64
Age          float64
KM           float64
FuelType      object
HP            object
MetColor     float64
Automatic      int64
CC             int64
Doors         object
Weight         int64
dtype: object

In [79]:
data_csv.select_dtypes(include="Int64",exclude=['object'])

Price  Automatic    CC  Weight
0     13500          0  2000    1165
1     13750          0  2000    1165
2     13950          0  2000    1165
3     14950          0  2000    1165
4     13750          0  2000    1170
...     ...        ...   ...     ...
1431   7500          0  1300    1025
1432  10845          0  1300    1015
1433   8500          0  1300    1015
1434   7250          0  1300    1015
1435   6950          0  1600    1114

[1436 rows x 4 columns]

In [80]:
data_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1436 entries, 0 to 1435
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Price      1436 non-null   int64  
 1   Age        1336 non-null   float64
 2   KM         1421 non-null   float64
 3   FuelType   1336 non-null   object 
 4   HP         1436 non-null   object 
 5   MetColor   1286 non-null   float64
 6   Automatic  1436 non-null   int64  
 7   CC         1436 non-null   int64  
 8   Doors      1436 non-null   object 
 9   Weight     1436 non-null   int64  
dtypes: float64(3), int64(4), object(3)
memory usage: 155.7+ KB


In [81]:
import numpy as np

In [82]:
np.unique(data_csv['CC'])


array([1300, 1332, 1398, 1400, 1587, 1598, 1600, 1800, 1900, 1975, 1995,
       2000], dtype=int64)

In [83]:
data_csv['MetColor'].dtype

dtype('float64')

In [84]:
data_csv['Price']=data_csv['Price'].astype('Float64')

In [85]:
data_csv["Price"].dtype

Float64Dtype()

In [86]:
data_csv['FuelType']=data_csv['FuelType'].astype('category')

In [87]:
data_csv['Doors'].nbytes

11488

In [88]:
data_csv['Doors'].dtype

dtype('O')

In [89]:
data_csv['Doors']=data_csv['Doors'].astype("category")


In [90]:
data_csv['Doors'].dtype

CategoricalDtype(categories=['2', '3', '4', '5', 'five', 'four', 'three'], ordered=False, categories_dtype=object)

In [91]:
data_csv['Doors'].nbytes

1492

In [92]:
data_csv['Doors'].replace("three",3,inplace=True)
data_csv['Doors'].replace("four",4,inplace=True)
data_csv['Doors'].replace("five",5,inplace=True)


In [93]:
data_csv['Doors'].dtype

CategoricalDtype(categories=['2', '3', '4', '5', 'five', 'four', 'three'], ordered=False, categories_dtype=object)

In [94]:
data_csv['Doors']

0       3
1       3
2       3
3       3
4       3
       ..
1431    3
1432    3
1433    3
1434    3
1435    5
Name: Doors, Length: 1436, dtype: category
Categories (7, object): ['2', '3', '4', '5', 5, 4, 3]

In [95]:
data_csv['Doors']=data_csv['Doors'].astype('int64')

In [96]:
data_csv['Doors']

0       3
1       3
2       3
3       3
4       3
       ..
1431    3
1432    3
1433    3
1434    3
1435    5
Name: Doors, Length: 1436, dtype: int64

In [97]:
data_csv['Doors'].dtypes

dtype('int64')

In [98]:
data_csv.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [99]:
data_csv

Price   Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500.0  23.0  46986.0   Diesel   90       1.0          0  2000      3   
1     13750.0  23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950.0  24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950.0  26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750.0  30.0  38500.0   Diesel   90       0.0          0  2000      3   
...       ...   ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500.0   NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845.0  72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500.0   NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250.0  70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950.0  76.0      1.0   Petrol  110       0.0          0  1600      5   

      Weight  
0       1165  
1       1165  
2       1165  
3       1165  
4       1170  
...      ...  
1431    1025  
1432    1015  
1433    1015  
1434    1015  
1435    1114  

[1436 rows x 10 columns]

In [100]:
data_csv.insert(9,'kmranges',"%")

In [101]:
data_csv

Price   Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500.0  23.0  46986.0   Diesel   90       1.0          0  2000      3   
1     13750.0  23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950.0  24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950.0  26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750.0  30.0  38500.0   Diesel   90       0.0          0  2000      3   
...       ...   ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500.0   NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845.0  72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500.0   NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250.0  70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950.0  76.0      1.0   Petrol  110       0.0          0  1600      5   

     kmranges  Weight  
0           %    1165  
1           %    1165  
2           %    1165  
3           %    1165  
4           %    1170  
...       ...     ...  
1431        %    1025  
1432        %    1015  
1433        %    1015  
1434        %    1015  
1435        %    1114  

[1436 rows x 11 columns]

In [102]:
for i in range(0,len(data_csv['KM'])):
    if(data_csv.at[i,'KM']<40000):
        data_csv.at[i,'knrange']="low"
    else:
         data_csv.at[i,'knrange']="high"

In [103]:
data_csv

Price   Age       KM FuelType   HP  MetColor  Automatic    CC  Doors  \
0     13500.0  23.0  46986.0   Diesel   90       1.0          0  2000      3   
1     13750.0  23.0  72937.0   Diesel   90       1.0          0  2000      3   
2     13950.0  24.0  41711.0   Diesel   90       NaN          0  2000      3   
3     14950.0  26.0  48000.0   Diesel   90       0.0          0  2000      3   
4     13750.0  30.0  38500.0   Diesel   90       0.0          0  2000      3   
...       ...   ...      ...      ...  ...       ...        ...   ...    ...   
1431   7500.0   NaN  20544.0   Petrol   86       1.0          0  1300      3   
1432  10845.0  72.0      NaN   Petrol   86       0.0          0  1300      3   
1433   8500.0   NaN  17016.0   Petrol   86       0.0          0  1300      3   
1434   7250.0  70.0      NaN      NaN   86       1.0          0  1300      3   
1435   6950.0  76.0      1.0   Petrol  110       0.0          0  1600      5   

     kmranges  Weight knrange  
0           %    1165    high  
1           %    1165    high  
2           %    1165    high  
3           %    1165    high  
4           %    1170     low  
...       ...     ...     ...  
1431        %    1025     low  
1432        %    1015    high  
1433        %    1015     low  
1434        %    1015    high  
1435        %    1114     low  

[1436 rows x 12 columns]

In [104]:
print(data_csv['knrange'].value_counts())
data_csv.drop(['kmranges','kmrange'],axis=1,inplace=True)

knrange
high    1120
low      316
Name: count, dtype: int64


KeyError: "['kmrange'] not found in axis"

In [ ]:
data_csv

In [ ]:
data=data_csv.copy(deep=False)

In [ ]:
data

In [ ]:
data.insert(10,'age in years',0)

In [ ]:
data

In [ ]:
def age_converted(age):
    age=age/12;
    return age



In [ ]:
#exploratory data analysis


In [ ]:
pd.crosstab(index=data['FuelType'],columns="frequency",dropna=True)

In [ ]:
pd.crosstab(index=data['Automatic'],columns=data['FuelType'],dropna=True)

In [ ]:
pd.crosstab(index=data['Automatic'],columns=data['FuelType'],dropna=True,normalize=True)

In [ ]:
pd.crosstab(index=data['Automatic'],columns=data['FuelType'],dropna=True,normalize=True,margins=True)

In [ ]:
pd.crosstab(index=data['Automatic'],columns=data['FuelType'],dropna=True,margins=True,normalize='index')

In [ ]:
numerical=data.select_dtypes(exclude=['object','category'])

In [ ]:
numerical

In [ ]:
numerical.corr()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn 

In [ ]:
data.dropna(axis=0,inplace=True)

In [ ]:
plt.scatter(data['Age'],data['Price'],c="pink")
plt.title("price and age graph")
plt.xlabel("Age")
plt.ylabel("price")
plt.show()

In [ ]:
data.isnull().sum()

In [ ]:
d=pd.read_csv("Toyota.csv",na_values=['??'],index_col=0)

In [ ]:
d

In [ ]:
d.isnull().sum()


In [ ]:
missing=d[d.isnull().any(axis=1)]

In [ ]:
missing

In [ ]:
d.describe()

In [ ]:
x=d['Age'].mean()


In [ ]:
x

In [ ]:
d['Age']=d['Age'].fillna(x)

In [ ]:
d.isnull().sum()

In [ ]:
d['KM'].fillna(d['KM'].median(),inplace=True)

In [ ]:
d.isna().sum()

In [ ]:
y=d['FuelType'].value_counts().index[0]

In [ ]:
d['FuelType'].fillna("hello",inplace=True)

In [ ]:
d.isnull().sum()

In [ ]:
#oops
class student:

    no_of_students=0
    def __init__(self,name,id,no):
        self.name=name
        self.id=id
        self.no=no
        student.no_of_students+=1
    def show_details(self):
        print(self.name,self.id,self.no)
s1=student("srikanth","s201081",9951720674)
s2=student("sravan","s201082",900012434)

s1.show_details()
s2.show_details()

print(student.no_of_students)
    